// haven-app/src/app/login/login.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  email:string
  password:string


  Submit():void {
    console.log(this.email)
    console.log(this.password)
  }

}

<mat-card align="center">
    <h1>Login</h1>
    
    <mat-form-field class="email" appearance="outline">
        <mat-label>E-mail</mat-label>
        <input matInput type="email" placeholder="exemplo@gmail.com.br" [(ngModel)]="email">
    </mat-form-field>
    <br>
    <mat-form-field class="password" appearance="outline">
        <mat-label>Password</mat-label>
        <input matInput type="password" [(ngModel)]="password">
    </mat-form-field>
    <br>
    <button (click)="onLogin()" mat-raised-button color="primary">Sign in</button>
    <br>
    <button mat-button color="primary">Don't have a registration yet?</button>
</mat-card>

// haven-app-react/src/components/Login.js
import React, { Component } from "react";

export default class Login extends Component {
    state = {

    }

    entrar = () => {
        console.log("entrar");
        return null;
    }

    irCadastrar = () => {
        console.log("irCadastrar");
    }

    render(){
        return (
            <div className = "container d-flex justify-content-center" >
                <div className="card mt-5 w-50">
                    <div className="card-body">
                        <div className="d-flex justify-content-center"><h1>Login</h1></div>
                        <form>
                            <div className="form-group mb-3">
                                <label htmlFor="nickName">E-mail</label>
                                <input
                                    type="text"
                                    className="form-control"
                                    id="nickName"
                                    placeholder="exemplo@gmail.com" />
                            </div>
                            <div className="form-group mb-3">
                                <label htmlFor="password">Senha</label>
                                <input
                                    type="password"
                                    className="form-control"
                                    id="password"
                                    placeholder="*******" />
                            </div>
                            <div className="d-flex justify-content-around">
                                <button type="submit" className="btn btn-primary" onClick={this.entrar}>Entrar</button>
                                <button type="submit" className="btn btn-link" onClick={this.irCadastrar}>Cadastrar-se</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        )
    }
}
